### DISCUSSION TITLE
How do I save configurations?

### DISCUSSION THREAD

**Discussion by gwolanin** [OctoPrint/docker#180] [Q&A]
Everything works great using docker-compose.
When I shut down the containers and start them back up, the configuration is gone.

Here is my docker-compose.yml

```
version: "3.3"

#volumes:
#  octoprint-docker1:
#  octoprint-docker2:

services:
  octoprint1:
    image: octoprint/octoprint
    ports:
      - 80:80
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      #- /home/pi/octoprint/octoprint-docker/1:/home/octoprint/
      - octoprint1:/home/octoprint/
    restart: always

  octoprint2:
    image: octoprint/octoprint
    ports:
      - 81:80
    devices:
      - /dev/ttyUSB1:/dev/ttyUSB1
    volumes:
      #- /home/pi/octoprint/octoprint-docker/2:/home/octoprint/
      - octoprint2:/home/octoprint/
    restart: always

volumes:
  octoprint1:
  octoprint2:
```
I'm probably most likely not understanding how docker volumes work.

**Comment by gwolanin** [comment]
I have figured out why my configurations aren't saved...

Under services, volumes.  I should have had - octoprint2:/octoprint

```
  octoprint2:
    image: octoprint/octoprint
    ports:
      - 81:80
    devices:
      - /dev/ttyUSB1:/dev/ttyUSB1
    volumes:
      #- /home/pi/octoprint/octoprint-docker/2:/home/octoprint/
      - octoprint2:/octoprint/
    restart: always
```
