### DISCUSSION TITLE
Can NOT get a single camera to work or...

### DISCUSSION THREAD

**Discussion by mikeoverbay** [OctoPrint/docker#221] [General]
I don't know what the address is.
I have 2 containers running. The cam is setup in the first one only but I can not get to it.
I can run the 2 OctoPrint web interfaces and they work with my 2 printers.
The Pi finds the camera fine. I can test it
This is the container code. Sorry it striped the white space alignment from it. I attached a text file of it also.

[Docker_Code.txt](https://github.com/OctoPrint/octoprint-docker/files/8191856/Docker_Code.txt)

version: '3.6'
services:
##### Octoprint1
  octoprint1:
    container_name: Octoprint1
    image: octoprint/octoprint
    hostname: Octoprint1
    restart: unless-stopped
    ports:
      - 5000:5000
      - 8080:8080
    volumes:
      - /home/dietpi/docker/octoprint1:/octoprint1
    environment:
      - ENABLE_MJPG_STREAMER=true
      - MJPG_STREAMER_INPUT=-n -d /dev/video0:/dev/video0 -r 1280x720 -f 30
    devices:
      #Printer Port
      - /dev/ttyACM0:/dev/ttyACM0
      #Webcam port
      #  - /dev/video0:/dev/video0
##### Octoprint2
  octoprint2:
    container_name: Octoprint2
    image: octoprint/octoprint
    hostname: Octoprint2
    restart: unless-stopped
    ports:
      - 5001:5000
      - 8081:8080
    volumes:
      - /home/dietpi/docker/octoprint2:/octoprint2
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

**Comment by Paraphraser** [comment]
What happens if you try it like this? 

```yaml
  octoprint1:
    container_name: Octoprint1
    image: octoprint/octoprint
    hostname: Octoprint1
    restart: unless-stopped
    ports:
    - 5000:5000
    - 8080:8080
    volumes:
    - /home/dietpi/docker/octoprint1:/octoprint1
    environment:
    - ENABLE_MJPG_STREAMER=true
    - MJPG_STREAMER_INPUT=-n -r 1280x720 -f 30
    - CAMERA_DEV=/dev/video0
    devices:
    - /dev/ttyACM0:/dev/ttyACM0
    - /dev/video0:/dev/video0
```

I use:

```yaml
    - MJPG_STREAMER_INPUT=-r 1152x648 -f 10
```

I'm not sure what `-n` does. I tried a few values but settled on 1152x648 as a reasonable "wide-screen" approximation for the Pi ribbon-cable camera. I think 10fps is the default frame-rate. That's the only value I've ever used. At 30fps I'd be a bit worried about the load (encoding, transmission) on the Pi 3B+ I'm using.

I've got some other notes in my docker-compose as follows:

```yaml
    # Octoprint configuration UI:
    #        Stream URL: /webcam/?action=stream
    #      Snapshot URL: http://localhost:8080/?action=snapshot
    #    Path to FFMPEG: /usr/bin/ffmpeg
```

Hope this helps.

**Reply by mikeoverbay** [reply]
Thank you for answering! 
Let me give this a try.
So far, I get two good containers but I can not access the camera.

**Comment by mikeoverbay** [comment]
What mode are you running the camera? Should it be in legacy mode?

**Comment by Paraphraser** [comment]
I'm sorry but I don't really understand your question. I am running Raspbian Buster because, as far as I'm aware, there is as yet no camera support for OctoPrint in Bullseye (or maybe it's FFMPEG that needs updating - I don't know). I think of Buster as the "legacy system" which has camera support for OctoPrint. It *might* mean the same thing as your question. Sorry to be so vague.

If there's a way of running either (a) Bullseye with Buster-style camera support that then works with FFMPEG and OctoPrint, or (b) OctoPrint on Bullseye such that FFMPEG/OctoPrint can use the native Bullseye camera system, I haven't come across it. I did some searching when Bullseye first became the official release but not since. I'd be interested to hear about any progress.

**Comment by mikeoverbay** [comment]
I appreciate the help.
I was just wondering if legacy setting in raspi-config needs enabled. I'm still struggling with this.  I think libcamera could be hijacking my camera.
This will launch the built in streamer fine but no image shows up anywhere.
I am going to reinstall everything. All this messing around with config files has probably broke it.
I saved this on my desktop. I should stream according to everything I have read and your help so the issue lies elsewhere.
```
services:
##### Octoprint1
  octoprint1:
    container_name: Octoprint1
    image: octoprint/octoprint
    hostname: Octoprint1
    restart: unless-stopped
    ports:
      - 5000:5000
      - 8080:8080
    volumes:
      - /home/dietpi/docker/octoprint1:/octoprint1
    environment:
      - ENABLE_MJPG_STREAMER=true
      - MJPG_STREAMER_INPUT=-r 1280x720 -f 30
      - CAMERA_DEV:/dev/video0
    devices:
      #Printer Port
      - /dev/ttyACM0:/dev/ttyACM0
      #Webcam port
      - /dev/video0:/dev/video0
##### Octoprint2
  octoprint2:
    container_name: Octoprint2
    image: octoprint/octoprint
    hostname: Octoprint2
    restart: unless-stopped
    ports:
      - 5001:5000
      - 8081:8080
    volumes:
      - /home/dietpi/docker/octoprint2:/octoprint2
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0


    # Octoprint configuration UI:
    #        Stream URL: /webcam/?action=stream
    #      Snapshot URL: http://localhost:8080/?action=snapshot
    #    Path to FFMPEG: /usr/bin/ffmpeg

```
