### DISCUSSION TITLE
Help to configure 2 webcams

### DISCUSSION THREAD

**Discussion by jerome6994** [OctoPrint/docker#273] [Q&A]
Good morning
I discovered octoprint in docker.

Suddenly I wanted to test 2 webcams but I'm having trouble!

my docker-compose is as follows :
```
services:
  octoprint:
    image: octoprint/octoprint
    container_name: octoprint
    restart: unless-stopped
    ports:
      - 5000:80
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/video0:/dev/video0
      - /dev/video2:/dev/video2
    volumes:
      - /appdata/octoprint:/octoprint
    environment:
      - TZ=Europe/Paris
      - ENABLE_MJPG_STREAMER=true
  
    networks:
      - octoprint-network

networks:
  octoprint-network:
volumes:
  octoprint:
```

In the multicam plugin I don't see at all what to put as URL!
I didn't understand in the documentation /webcam/<device_name>/?action=stream
Where can I find this device_name?

My configuration of the multicam plugin is
![image](https://github.com/user-attachments/assets/c306cb06-e593-454d-a8f8-587e61d5bb76)

```
Default
/webcam/?action=stream
http://127.0.0.1:8080/?action=snapshot
```

```
webcam1
http://192.168.1.213:8081/?action=stream
http://127.0.0.1:8081/?action=snapshot
```

When I plug in my webcam n°2 then I have video2 and video3 which appear
![image](https://github.com/user-attachments/assets/1b7ccc6e-9317-4798-90bf-9e13aabb9903)

Thank you for your help 

Jerome
