### ISSUE TITLE
Persistent Configuration and Plugins

### ISSUE THREAD

**Issue by JoschaMiddendorf** [OctoPrint/docker#10]
Which volumes do I have to map outside the container to make my configuration and installed plugins persistent across updates?

**Comment by gaetancollaud** [comment]
Normally `/home/octoprint/.octoprint` should be enough. Do you use the [docker-compose](https://github.com/OctoPrint/docker/blob/master/docker-compose.yml) file ?

**Comment by JoschaMiddendorf** [comment]
No as I’m using UnRaid OS docker compose isn’t supported. I’m using a huge generated docker run command and with only .octoprint mounted all plugins are gone after any updates.

**Comment by stickystyle** [comment]
I just came across this as well, the issue is that plugins that are installed via the plugin manager get put into the venv where Octoprint is running, namely `/opt/octoprint/venv/lib/python2.7/site-packages/` and this dir isn't exported as a volume (I'm not sure you would want to).
I've only been playing with Octoprint for the last 8 hours, but I'm thinking perhaps passing `-t /home/octoprint/.octoprint/plugins` option to PIP from the plugin manager should get the plugins into the volume so they are not lost when the container is recreated.

**Comment by TheFitzZZ** [comment]
@stickystyle could you please elaborate on the parameter passing you mentioned?

**Comment by DanielJoyce** [comment]
No need for that. Just need to configure the docker-compose volumes properly.

**Comment by TheFitzZZ** [comment]
@DanielJoyce we already established that this is not the case.

**Comment by balert** [comment]
I've had the same problem and found a really hacky solution for it. Seems to work for me. 
The trick was similar to what @stickystyle proposed.

Well, -t /home/octoprint/.octoprint/plugins didn't work for me. Once I've figured out you can pass pip options in the octoprint settings under plugin manager I've tried this, and it didn't work because the plugin folder was empty and the installation of a plugin required the "OctoPrint" package as a dependency. Fiddled around a bit with this but it didn't work.

Then I thought I might just mount the site-package directory, as also proposed by @stickystyle but this didn't work either because it needed to be populated first, and coulnd't be empty. 

So what I did so solve this was to mount a volume "venv" from outside to "/venv" inside the container and then get a bash inside the container (docker-compose exec octoprint bash) and copy the contents of /opt/octoprint/venv to /venv. Then I stopped the container and mounted the outside "venv" directory to /opt/octoprint/venv, by this octoprint resides outside the container and plugins are persistent and work. 

However, clearly this isn't a good solution, I'm happy about any hints or tips to get this working.

**Comment by JoschaMiddendorf** [comment]
That’s exactly what I did as a workaround.

**Comment by balert** [comment]
> That’s exactly what I did as a workaround.

nice,  I just thought I could comment this here, so others can save time, and might help.

**Comment by JoschaMiddendorf** [comment]
Just to be exact. I just mounted /opt/octoprint/venv/lib/python2.7/site-packages/ not the whole /opt/octoprint/venv.

**Comment by TheFitzZZ** [comment]
That's what I did a few months ago - unfortunately that broke later on, as updates within the updated docker image itself wrecked it. So you could argue: don't update the image, always update through the updater :-)

**Comment by balert** [comment]
@JoschaMiddendorf in my case only site-packages didn't suffice. Don't recall the details.

**Comment by johny-mnemonic** [comment]
Check [this commit](https://github.com/nunofgs/docker-octoprint/commit/e9ef24193b440d0d4313126b6c8088769e09090d). This solution seems to work fine.

**Comment by ViolentCrumble** [comment]
> 
> 
> I've had the same problem and found a really hacky solution for it. Seems to work for me.
> The trick was similar to what @stickystyle proposed.
> 
> Well, -t /home/octoprint/.octoprint/plugins didn't work for me. Once I've figured out you can pass pip options in the octoprint settings under plugin manager I've tried this, and it didn't work because the plugin folder was empty and the installation of a plugin required the "OctoPrint" package as a dependency. Fiddled around a bit with this but it didn't work.
> 
> Then I thought I might just mount the site-package directory, as also proposed by @stickystyle but this didn't work either because it needed to be populated first, and coulnd't be empty.
> 
> So what I did so solve this was to mount a volume "venv" from outside to "/venv" inside the container and then get a bash inside the container (docker-compose exec octoprint bash) and copy the contents of /opt/octoprint/venv to /venv. Then I stopped the container and mounted the outside "venv" directory to /opt/octoprint/venv, by this octoprint resides outside the container and plugins are persistent and work.
> 
> However, clearly this isn't a good solution, I'm happy about any hints or tips to get this working.

could you provide any clearer instructions on the commands required to do this? having some trouble.

**Comment by ViolentCrumble** [comment]
I think i am finally getting closer,  This is my docker-compose file, basically i am running 2instances of octoprint and everything boots up fine. I install a plugin and cannot for the life of me workout how to restart octoprint.. I use docker restart <containerID> and it restarts and the plugin shows up.

However when i use docker-compose down and then use docker-compose up again the plugin is gone.

Is this the correct way to mount the venv directory? This is running on ubuntu 18.04. I have tried using ./Public/venv1 and also tried using ./venv. I have tried /home/octoprint/venv and /opt/octoprint/venv

nothing seems to persist after a docker-compose down. For now it is usable but useless to me, if the power goes out or something else i will have to configure everything all over again.

Any help would be appreciated. thanks!

```
version: '3.2'

volumes:
  octoprint-docker:
  octoprint-docker2:
  ffmpeg1:
  ffmpeg2:
services:
  octoprint1:
    image: octoprint/octoprint
    ports:
      - 5000:5000
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - octoprint-docker:/home/octoprint/.octoprint
      - ffmpeg1:/home/ffmpeg
      - ./venv1:/home/octoprint/venv
    restart: always

  streamer1:
    build: .
    ports:
      - 8911:8080
    devices:
      - /dev/video1:/dev/video0
    environment:
      - MJPG_RES=640x480
      - MJPG_FPS=25
      - MJPG_USER=admin
      - MJPG_PASS=adm1n
    restart: always

  octoprint2:
    image: octoprint/octoprint
    ports:
      - 5001:5000
    devices:
      - /dev/ttyUSB1:/dev/ttyUSB1
    volumes:
      - octoprint-docker2:/home/octoprint/.octoprint
      - ffmpeg2:/home/ffmpeg
      - ./venv2:/home/octoprint/venv
    restart: always

  streamer2:
    build: .
    ports:
      - 8912:8080
    devices:
      - /dev/video0:/dev/video0
    environment:
      - MJPG_RES=1280x720
      - MJPG_FPS=60
      - MJPG_USER=admin
      - MJPG_PASS=adm1n
    restart: always
```
